---
title: "randomf"
output: html_document
date: "2024-02-09"
---

```{r}
library(randomForest)
data <- read.csv("C:/Users/szxia/Downloads/cleaned_data.csv")
data_new <- data[,-grep("SPENDING",colnames(data))]
train_size <- 0.8
train_index <- 1:round(train_size * nrow(data_new))
train_data <- data_new[train_index, ]
test_data <- data_new[-train_index, ]

train_dataS <- data[train_index, ]
test_dataS <- data[-train_index, ]
model <- randomForest(x = train_data, y = train_dataS$SPENDING, importance=TRUE, method="regression")
```

```{r}
predictions <- predict(model, test_dataS)
rmse <- sqrt(mean((test_dataS$SPENDING - predictions)^2))
print(rmse)

actual_vs_predicted <- data.frame(Actual = test_dataS$SPENDING, Predicted = predictions)
print(actual_vs_predicted)


importance <- importance(model, type=1)

print(importance)

```

```{r}
library(ggplot2)
data_to_plot <- data.frame(SampleIndex = 1:length(test_dataS$SPENDING), Actual = test_dataS$SPENDING, Predicted = predictions)

ggplot(data_to_plot, aes(x = SampleIndex)) + 
  geom_line(aes(y = Actual, colour = "Actual")) + 
  geom_line(aes(y = Predicted, colour = "Predicted"), linetype = "dashed") +
  scale_color_manual("", 
                     breaks = c("Actual", "Predicted"),
                     values = c("Actual" = "blue", "Predicted" = "red")) +
  labs(title = "Actual vs. Predicted Healthcare Spending",
       x = "Sample Index",
       y = "Spending") +
  theme_minimal()
```

```{r}
residuals <- residuals(model, test_dataS)

predictions <- predict(model, test_dataS)

plot(predictions, residuals, xlab = "Predicted", ylab = "Residuals", main = "Residual Plot")
abline(h = 0, col = "grey", lty = 2) 
lines(lowess(predictions, residuals), col = "red") 
```
